Config = {}

Config.Locale = 'de' -- Translation en, de you can add more

Translation = {
    ['de'] = {
        ['close_item_title'] = 'Schließen',
        ['close_item_description'] = '',
        ['command_no_access'] = '~r~Du hast hierauf keinen zugriff!',
        ['create_key_locker_menu_title'] = 'Key Locker erstellen',
        ['coord_x_item_title'] = 'X:',
        ['coord_x_item_description'] = '',
        ['coord_y_item_title'] = 'Y:',
        ['coord_y_item_description'] = '',
        ['coord_z_item_title'] = 'Z:',
        ['coord_z_item_description'] = '',
        ['size_item_title'] = 'Größe:',
        ['size_item_description'] = '',
        ['input_size'] = 'Gebe die Größe ein',
        ['access_submenu_title'] = 'Zugriff',
        ['access_submenu_description'] = '',
        ['password_item_title'] = 'Passwort:',
        ['password_item_description'] = '',
        ['input_password'] = 'Gebe ein Passwort ein',
    },
    ['en'] = {
        ['close_item_title'] = 'close',
        ['close_item_description'] = '',
        ['command_no_access'] = '~r~Du hast hierauf keinen zugriff!',
        ['coord_x_item_title'] = 'X:',
        ['coord_x_item_description'] = '',
        ['coord_y_item_title'] = 'Y:',
        ['coord_y_item_description'] = '',
        ['coord_z_item_title'] = 'Z:',
        ['coord_z_item_description'] = '',
        ['size_item_title'] = 'Größe:',
        ['size_item_description'] = '',
        ['input_size'] = 'Gebe die Größe ein',
        ['access_submenu_title'] = 'Zugriff',
        ['access_submenu_description'] = '',
        ['password_item_title'] = 'Passwort:',
        ['password_item_description'] = '',
        ['input_password'] = 'Gebe ein Passwort ein',
    },
}